facilities:
  - name: ポロト
    url: https://hoshinoresorts.com/plans/JA/0000000129/0000000063
  - name: 津軽
    url: https://hoshinoresorts.com/plans/JA/0000000114/0000000431
  - name: 秋保
    url: https://hoshinoresorts.com/plans/JA/0000000133/0000000016
  - name: 鬼怒川
    url: https://hoshinoresorts.com/plans/JA/0000000121/0000000173
  - name: 箱根
    url: https://hoshinoresorts.com/plans/JA/0000000117/0000000338
  - name: 仙石原
    url: https://hoshinoresorts.com/plans/JA/0000000124/0000000116
  - name: アンジン
    url: https://hoshinoresorts.com/plans/JA/0000000122/0000000092
  - name: 伊東
    url: https://hoshinoresorts.com/plans/JA/0000000108/0000000523
  - name: 遠州
    url: https://hoshinoresorts.com/plans/JA/0000000113/0000000566
  - name: アルプス
    url: https://hoshinoresorts.com/plans/JA/0000000123/0000000079
  - name: 奥飛騨
    url: https://hoshinoresorts.com/plans/JA/0000000134/0000000022
  - name: 加賀
    url: https://hoshinoresorts.com/plans/JA/0000000103/0000000506
  - name: 玉造
    url: https://hoshinoresorts.com/plans/JA/0000000106/0000000512
  - name: 出雲
    url: https://hoshinoresorts.com/plans/JA/0000000132/0000000028
  - name: 長門
    url: https://hoshinoresorts.com/plans/JA/0000000126/0000000040
  - name: 雲仙
    url: https://hoshinoresorts.com/plans/JA/0000000131/0000000083
  - name: 別府
    url: https://hoshinoresorts.com/plans/JA/0000000128/0000000088
  - name: 由布院
    url: https://hoshinoresorts.com/plans/JA/0000000130/0000000066
  - name: 阿蘇
    url: https://hoshinoresorts.com/plans/JA/0000000115/0000000428
  - name: 霧島
    url: https://hoshinoresorts.com/plans/JA/0000000127/0000000086
